apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-hpmc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-hpmc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-hpmc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-hpmc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-hpmc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xjiv-tenant/rhtap-demo-app/hacbs-test-project-hpmc@sha256:9a1de6afa47981d99c8f2d89df898922905e72ce9a072df47f47182c914f7c26
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
